Repository B3Partners/planmonitor-wonen-api, pull requests merged in 2025-01, with the labels that each got.

#170 Change knelpunten_meerkeuze to array
  src/main/java/nl/b3p/planmonitorwonen/api/PlanmonitorWonenDatabaseService.java
  src/main/java/nl/b3p/planmonitorwonen/api/configuration/PopulateTestData.java
  src/main/java/nl/b3p/planmonitorwonen/api/model/Planregistratie.java
  src/main/resources/db/migration/V2__knelpunten_meerkeuze_array.sql
Labels: enhancement

#174 Dependency management
  pom.xml
Labels: dependency

#175 PMW-46: make it possible to push (tagged) images using Maven
  .github/maven-settings.xml
  .github/workflows/codeql-analysis.yml
  .github/workflows/owasp-dependency-check.yml
  .github/workflows/qa.yml
  .github/workflows/ubuntu-maven.yml
  pom.xml
Labels: infrastructure
